import FWCore.ParameterSet.Config as cms

process = cms.Process("wNTuple")

process.load("TerraNova.NtupleMaker.wAnalysis_MC_cff")


process.options   = cms.untracked.PSet( wantSummary = cms.untracked.bool(True) )
process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
process.MessageLogger.cerr.FwkReport.reportEvery = 1000

#process.load("FWCore.MessageLogger.MessageLogger_cfi")
#process.MessageLogger = cms.Service("MessageLogger")
#process.MessageLogger.destinations = ['cout']
#process.MessageLogger.cout = cms.untracked.PSet(
#    threshold = cms.untracked.string('INFO'),
#    FwkReport = cms.untracked.PSet(reportEvery=cms.untracked.int32(1000))
#)

process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(



			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_100_1_JO0.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_101_1_b5j.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_10_1_vyo.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_102_1_uPi.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_103_2_ecB.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_104_1_u28.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_105_1_J2h.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_106_1_KTj.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_107_5_KaG.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_108_1_HM3.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_109_2_oCM.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_110_5_eip.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_111_1_BQr.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_11_1_aQj.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_112_1_HOh.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_113_1_66t.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_114_2_mev.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_115_1_Jwt.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_116_5_KY9.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_117_1_FiN.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_118_1_XSp.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_119_5_PbD.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_1_1_CAJ.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_120_1_Lcc.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_121_1_WMt.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_12_1_g8D.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_122_2_0sH.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_123_2_bNT.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_124_1_qKQ.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_125_1_jYr.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_126_1_0ZQ.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_127_1_s5O.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_128_1_Dsb.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_129_1_vkl.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_130_1_eDY.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_131_1_nij.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_13_1_WOe.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_132_1_ys3.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_133_1_ffr.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_134_1_GqT.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_135_1_7of.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_136_1_MiO.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_137_1_q2c.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_138_1_EB3.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_139_2_Q7h.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_140_1_CzU.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_141_1_mg1.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_14_1_1pk.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_142_1_Huy.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_143_3_64F.root',
      			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_144_1_4Zn.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_145_1_SCS.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_146_1_PZ6.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_147_1_i4W.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_148_1_hK8.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_149_1_zla.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_150_1_1wY.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_151_1_ZVc.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_15_1_zDg.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_152_5_7GU.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_153_1_sOd.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_154_1_m3o.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_155_1_slY.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_156_1_ZdM.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_157_1_sIA.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_158_1_rUh.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_159_1_CPA.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_160_1_R8y.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_161_2_8oC.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_16_1_rJV.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_162_1_1uy.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_163_1_eV3.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_164_1_j6Q.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_165_1_UJa.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_166_1_fOG.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_167_5_JL8.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_168_2_AFB.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_169_1_CxZ.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_170_1_pGQ.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_171_1_9IO.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_17_1_ZdV.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_172_1_V4K.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_173_1_fb9.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_174_2_8wV.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_175_1_5XJ.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_176_1_GB2.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_177_1_2QM.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_178_1_0JA.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_179_1_LKs.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_180_1_V8s.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_181_1_azi.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_18_1_ktt.root',
			'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_182_1_Yuh.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_183_1_D9k.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_184_1_83t.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_185_1_xil.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_186_1_KGw.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_187_1_GNp.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_188_1_8fb.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_189_1_YPC.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_190_1_BD8.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_191_1_1tn.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_19_1_AKx.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_192_1_UX3.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_193_1_jFu.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_194_1_Wg7.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_195_1_poL.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_196_1_tBT.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_197_1_Z4T.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_198_5_0F6.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_199_1_tjr.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_200_1_dYD.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_201_1_6Iy.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_20_1_Njk.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_202_1_KDi.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_203_1_LBT.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_204_1_qFF.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_205_1_Wuv.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_206_1_zNd.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_207_1_3O9.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_208_2_i9I.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_209_1_6wh.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_210_5_JLe.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_211_1_IPD.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_21_1_Ozt.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_212_1_qZ5.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_213_1_lYf.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_214_2_4o1.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_215_1_wJg.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_216_1_u5W.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_217_1_b7y.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_218_1_aFA.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_219_1_oBX.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_2_1_lpF.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_220_3_D2M.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_221_1_ih7.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_22_1_KuF.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_222_2_8JA.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_223_1_NIh.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_224_1_lsZ.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_225_1_cpW.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_226_1_Nnc.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_227_5_JzX.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_228_1_nOD.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_229_1_jlT.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_230_1_rRk.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_231_5_LJg.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_23_1_XgZ.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_232_2_LcR.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_233_1_gul.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_234_1_elv.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_235_1_wCI.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_236_1_OL6.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_237_1_DXn.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_238_1_8XN.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_239_1_Izv.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_240_1_wBg.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_241_1_FWJ.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_24_1_qSF.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_25_1_vmu.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_26_1_ngt.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_27_1_LZT.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_28_1_UmH.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_29_1_G6w.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_30_1_7f0.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_31_1_djN.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_3_1_6cI.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_32_1_7Dj.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_33_1_GdG.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_34_1_ylH.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_35_1_cnT.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_36_1_wFy.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_37_1_fFA.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_38_1_AML.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_39_1_TDq.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_40_1_kfO.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_41_1_kZa.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_4_1_yqK.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_42_1_WOZ.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_43_1_6Cp.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_44_1_JuV.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_45_1_dKm.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_46_1_aDv.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_47_1_kqJ.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_48_1_oBu.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_49_1_5dp.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_50_1_29X.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_51_1_yBH.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_5_1_V3G.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_52_1_Tv8.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_53_1_mkK.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_54_1_5Eo.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_55_1_wkt.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_56_1_8za.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_57_1_hnq.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_58_1_3Jv.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_59_1_CeP.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_60_2_p0K.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_61_1_tOI.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_6_1_axq.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_62_1_MxJ.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_63_1_gVX.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_64_1_abo.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_65_1_E09.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_66_1_1lW.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_67_1_om4.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_68_1_ery.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_69_1_0OR.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_70_1_oqj.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_71_1_Uvm.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_7_1_yS9.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_72_1_D9e.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_73_1_WpY.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_74_1_6wB.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_75_1_HrA.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_76_1_XeE.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_77_1_WCc.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_78_1_PJf.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_79_1_wRi.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_80_1_PhO.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_81_1_meO.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_8_1_W6n.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_82_1_qVy.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_83_1_l6h.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_84_1_CC1.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_85_1_wOx.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_86_1_Ql5.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_87_1_KM4.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_88_1_dG7.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_89_1_y1F.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_90_1_Q9K.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_91_1_OIb.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_9_1_RBg.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_92_1_Hbe.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_93_1_So2.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_94_1_V3J.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_95_1_cHC.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_96_1_Z6n.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_97_1_XdM.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_98_2_nKp.root',
    'file:/d2/scratch/Storage_Area/Wpt-skim/Electron_evtClean/MC/WplusToENu/patTuple_skim_99_1_iKc.root',







)
)

process.TFileService = cms.Service("TFileService",
    fileName = cms.string('wNTuple.root')
)

#process.load("TerraNova.NtupleMaker.Sources.SingleEle_MC_Local_cff")

process.p = cms.Path(
    process.WEleNeuAnalysisMCSequence
)

